// 合同 PDF 生成器。
// 注：gofpdf 默认字体不支持中文；本实现用 ASCII 摘要生成演示 PDF，
// 生产建议替换为 Chromium headless（puppeteer）+ HTML 模板，或加载 CJK 字体。
package contractpdf

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// ContractData 合同 PDF 渲染参数。
type ContractData struct {
	ContractID         string
	CustomerName       string
	PackageName        string
	PurchasingEnergy   float64
	GreenPowerRatio    float64
	PurchaseStartMonth string
	PurchaseEndMonth   string
	Status             string
}

// Generate 生成 PDF 字节流。
func Generate(d ContractData) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()

	// 标题
	pdf.SetFont("Helvetica", "B", 18)
	pdf.CellFormat(0, 12, "Electricity Retail Contract", "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.CellFormat(0, 6, "PTIS generated · "+time.Now().Format("2006-01-02 15:04"), "", 1, "C", false, 0, "")
	pdf.Ln(10)

	// 合同号
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(0, 8, "Contract No.: "+d.ContractID, "", 1, "L", false, 0, "")
	pdf.Ln(5)

	// 关键信息表
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(50, 8, "Item", "1", 0, "C", false, 0, "")
	pdf.CellFormat(0, 8, "Value", "1", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 11)

	rows := [][2]string{
		{"Customer", d.CustomerName},
		{"Package", d.PackageName},
		{"Purchase Energy (MWh)", fmt.Sprintf("%.2f", d.PurchasingEnergy)},
		{"Green Power Ratio", fmt.Sprintf("%.1f%%", d.GreenPowerRatio)},
		{"Period", d.PurchaseStartMonth + " ~ " + d.PurchaseEndMonth},
		{"Status", d.Status},
	}
	for _, r := range rows {
		pdf.CellFormat(50, 8, r[0], "1", 0, "L", false, 0, "")
		pdf.CellFormat(0, 8, r[1], "1", 1, "L", false, 0, "")
	}
	pdf.Ln(10)

	// 条款
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(0, 8, "Terms and Conditions", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	terms := []string{
		"1. The Buyer shall purchase the contracted electricity from the Seller during the contract period.",
		"2. The settlement shall follow the Operating Rules of the Power Market.",
		"3. Force majeure events shall be handled in accordance with relevant laws and regulations.",
		"4. Any modification to this contract shall be made in writing and signed by both parties.",
		"5. This contract is generated by PTIS and serves as a structured summary; the formal contract shall prevail.",
	}
	for _, t := range terms {
		pdf.MultiCell(0, 6, t, "", "L", false)
		pdf.Ln(1)
	}
	pdf.Ln(10)

	// 签字栏
	pdf.SetFont("Helvetica", "", 11)
	pdf.CellFormat(85, 30, "Buyer (signature):", "T", 0, "L", false, 0, "")
	pdf.CellFormat(0, 30, "Seller (signature):", "T", 1, "L", false, 0, "")
	pdf.Ln(5)
	pdf.SetFont("Helvetica", "", 9)
	pdf.CellFormat(0, 6, "Generated by PTIS · "+d.ContractID, "", 1, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
